all: comparesort1.out comparesort2.out comparesort3.out

comparesort1.out : comparesort.c define.h
	gcc -o comparesort1.out comparesort.c -O2

comparesort2.out : comparesort2.c define.h
	gcc -o comparesort2.out comparesort2.c -O2

comparesort3.out : comparesort3.c define.h
	gcc -o comparesort3.out comparesort3.c -O2


